### ISSUE TITLE
Attempting to use this with Foundation-sites 6.2.1

### ISSUE THREAD

**Issue by cfator** [aexmachina/ember-cli-sass#102]
When running the Ember Server I'm getting:
Attempting to watch missing directory: bower_components/foundation/scss

**Comment by aexmachina** [comment]
I'm guessing it's because that directory doesn't exist. What's the path to the SCSS files in the foundation bower package?

**Comment by tgsoverly** [comment]
Because foundation is "foundation-sites" in 6+

**Comment by aexmachina** [comment]
Thanks @tgsoverly
