### ISSUE TITLE
Error when using .sass extension instead of .scss

### ISSUE THREAD

**Issue by Trendy** [aexmachina/ember-cli-sass#103]
I'm observing an odd error when using .sass extensions instead of .scss.

The following options:

```javascript
var app = new EmberApp(defaults, {
    sassOptions: {
        extension: 'sass'
    }
  });
```

Yield... 

> Invalid CSS after ".a0-icon-badge {": expected "}", was "{"
Error: Invalid CSS after ".a0-icon-badge {": expected "}", was "{"
    at options.error (/home/jeremiah/dev/flow/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/lib/index.js:277:32)

Here's the SASS file:

```css
.a0-icon-badge {
  display: none !important;
}
```

The error disappears when I put everything on one line or change the file extension to .scss and remove the option in ember-cli-build.js.

**Comment by aexmachina** [comment]
SASS uses significant white space:

```sass
.a0-icon-badge
  display: none !important
```

**Comment by Trendy** [comment]
*derp* I just started using SASS in a personal project, didn't realize there was a syntax difference between the file extensions. Thanks @aexmachina
