### ISSUE TITLE
Relative path parent imports not working as expected

### ISSUE THREAD

**Issue by jrhorn424** [aexmachina/ember-cli-sass#111]
I'm trying to use [Picnic](http://picnicss.com) with `ember-cli-sass`.

```js
// ember-cli-build.js
    sassOptions: {
      includePaths: [
        'bower_components/picnic/src',
      ]
    }
```

```scss
// app.scss
@import 'picnic';
```

The build fails with:

```
Build failed.
File: /Users/jeffh/teaching/wdi/boston/listr-client/tmp/sass_compiler-input_base_path-rdL8XbSY.tmp/1/picnic.scss (5)
The Broccoli Plugin: [SassCompiler] failed with:
Error: File to import not found or unreadable: ../themes/default/theme
```

```scss
// bower_components/picnic/src/picnic.scss
@import '../themes/default/theme';

@import '../bower_components/compass-breakpoint/stylesheets/breakpoint';

@import './plugins/normalize/plugin';
```

Here's the (abbreviated) structure of the picnic bower module.

```
bower_components/picnic
├── bower_components
│   ├── compass-breakpoint
│   └── sassy-maps
├── src
│   ├── picnic.scss
│   ├── plugins
└── themes
    ├── default
    │   ├── _colors.scss
    │   └── _theme.scss
    └── squared
        ├── _colors.scss
        ├── _plugins.scss
        └── _theme.scss
```

I've verified that parent imports are the issue by commenting out the import of the theme and the breakpoints module. I've also tried moving the offending files into the `src` directory as siblings, adjusting the paths, and that works.

**Comment by aexmachina** [comment]
That's because `themes/` isn't being included in the Broccoli tree. You probably want:

```js
// ember-cli-build.js
    sassOptions: {
      includePaths: [
        'bower_components/picnic',
      ]
    }
```

```scss
// app.scss
@import 'src/picnic';
```

However you're then including the whole `picnic/bower_components/` directory in your tree, so YMMV. It's kinda an unfortunate directory structure in Picnic.

**Comment by aexmachina** [comment]
(Feel free to reopen if the issue's not resolved).

**Comment by jrhorn424** [comment]
> It's kinda an unfortunate directory structure in Picnic.

Is that the sort of thing you'd like fixed in a PR?

**Comment by jrhorn424** [comment]
Thanks, @aexmachina. I'll ping the folks over at picnic.
