### ISSUE TITLE
addon/styles/addon.scss not compiling to dist/assets/vendor.css

### ISSUE THREAD

**Issue by sky-coding** [aexmachina/ember-cli-sass#112]
Hello, I've been trying to include ember-cli-sass into a new ember-cli addon using the following documentation:

> ## Installation
> 
> ```
> ember install ember-cli-sass
> ```
> 
> 
> ## Addon Usage
> 
> To compile SASS within an ember-cli addon, there are a few additional steps:
> 
> 1. Include your styles in `addon/styles/addon.scss`.
> 
> 2. Ensure you've installed `ember-cli-sass` under `dependencies` in your
>    `package.json`.
> 
> ---

`ember install ember-cli-sass` adds `ember-cli-sass` into the `devDependencies` section of `package.json`, and sass compilation then works great for the dummy app and the app/styles folder. However, `addon/styles/addon.scss` was not being compiled into `dist/assets/vendor.css`. Simply moving `ember-cli-sass` from the `devDependencies` to the `dependencies` section of `package.json` solved this problem. It is very easy to overlook the `dependencies` specification in step 2 since it was added automatically using `ember install` and sass compilation works (partially) without any errors. I feel the documentation should be updated slightly to point out the `devDependencies`/`dependencies` distinction (or specify `npm i ember-cli-sass --save` for addon creators) to save others from the headache. Thanks!

**Comment by aexmachina** [comment]
Great thanks for the tip. I've updated the README.
