### ISSUE TITLE
IncludePaths scope

### ISSUE THREAD

**Issue by jcbvm** [aexmachina/ember-cli-sass#115]
Is it possible to add a scope to the included paths, so that the included paths do not conflict with any other resources in the app or addon. Something like this:

    var app = new EmberApp({
        sassOptions: {
            includePaths: {
                customBootstrapScope: '../../bower_components...../',
                someOtherScope: '../../bower_components....'
            }
         }
    });

So the final import will be something like `@import 'customBootstrapScope/bootstrap';`

**Comment by aexmachina** [comment]
This is a nice to have, but it's not a priority. You're welcome to provide a PR for this!
