### ISSUE TITLE
@if statements not working for some but not others

### ISSUE THREAD

**Issue by jeremytm** [aexmachina/ember-cli-sass#121]
We're seeing an issue where a new co-worker has setup our ember app to start working on it. All of the same versions are installed, but their copy is not processing sass @if statements properly, and skipping over any rules within these statements.

Can you think of any reason this could happen?

**Comment by aexmachina** [comment]
Probably npm and binary modules (node-sass is compiled). Simple solution is to `rm -rf node_modules`, or `npm rebuild node-sass` may do the trick.
