### ISSUE TITLE
ember build fails when using calc() function with 4 variables

### ISSUE THREAD

**Issue by AllwynSelvin** [aexmachina/ember-cli-sass#122]
Dear Team,

we are using ember-cli-sass version 5.2.1 for our application. It was working fine. But suddenly it failed in following scenario.

```
$a:2.15rem;
$b:3.15rem;
$b:4.15rem;
$c:5.15rem;
$componenet-wrapper{
height: calc(100% - (#{a}+#{b}+#{c}+#{d}));
}
```

This is failing 5.3.1 as well. Please verify.

Regards,
Allwyn

**Comment by aexmachina** [comment]
This module is a thin wrapper around node-sass. This is a node-sass issue, so please report it on the [node-sass repo](https://github.com/sass/node-sass/issues).
