### ISSUE TITLE
File to import not found or unreadable (anything outside of current directory)

### ISSUE THREAD

**Issue by barneycarroll** [aexmachina/ember-cli-sass#124]
I'm not sure if the problem is with ember-cli-sass or an upstream dependency, but I'm not able to import anything outside of the `app/styles` directory — in other words anything beginning with `../`. I'm on Windows, and apparently it prefers `./..` — that doesn't work either.

The issue described above was a regression in node_sass, but that was fixed a while back and for the purposes of that particular bug, the current dependency graph (for 5.3.1) should check out.

***

It might be that I'm missing a trick — maybe I could sidestep this issue if there was a recommended method of resolving SASS dependency imports that didn't involve crawling up the filesystem hierarchy?

**Comment by aexmachina** [comment]
Yeah, that's not supported by the underlying Broccoli build system.

**Comment by barneycarroll** [comment]
Don't suppose you've got a link to the upstream issue? The underlying problem is still pretty grave IMO. Thanks!

**Comment by aexmachina** [comment]
No, I'm afraid you misunderstand the problem. This is a result of design
decisions in the way Broccoli works, it's not an issue.

If you want to access the parent directory then you need to add the parent
directory to the Broccoli tree.

**Comment by barneycarroll** [comment]
I don't have any particular problem with that implementation detail. And I realise you could argue my pulling in Sass dependencies through NPM or Bower is a hack. Is there a recommended way of importing 3rd party Sass dependencies with ember-cli-sass?

**Comment by aexmachina** [comment]
There's nothing wrong with that. You can add the whole lot, but it'll slow down the file watching in dev mode. I'm not sure what the current state of the art is on this, but I've definitely done it before. Maybe just add the specific dependencies that you want to use.
