### ISSUE TITLE
SassCompiler Error after Ember 2.7 Upgrade

### ISSUE THREAD

**Issue by Aaronfischer** [aexmachina/ember-cli-sass#134]
Attempting to upgrade to ember 2.7 (ember-cli/data/ember). Results in an error when attempting to compile the application:

```
The Broccoli Plugin: [SassCompiler] failed with:
Error: File to import not found or unreadable: include-media
```

Ran a few smoke tests on this and removing the `@import 'include-media';` line and it then went on to the next case where I'm importing and failed there.

Here is a snippet from my ember-cli-build.js:

```
var app = new EmberApp(defaults, config, {
  sassOptions: {
    includePaths: [
      'bower_components/include-media/dist',
      'bower_components/open-sans-fontface'
    ]
  }
});
```

I don't see any oddities here, nothing has changed in any of my dependencies except for whatever the ember upgrades required. (I can of course confirm they exist in the bower_components)

Anything else you can think to check? Anyone else experiencing this as well?

**Comment by aexmachina** [comment]
The configuration is supposed to go in the second argument of the EmberApp constructor.

**Comment by Dhaulagiri** [comment]
@Aaronfischer I have been pulling my hair out trying to figure out the exact same problem trying to upgrade to ember-cli 2.7 and what @aexmachina pointed out is exactly what the problem was for me.  What we were passing in as the second argument was something we could delete so it  was an easy fix, but I'm not sure what changed in ember-cli that caused this.

**Comment by Aaronfischer** [comment]
@aexmachina @Dhaulagiri Yep, this does seem to be the fix, but we cannot delete our previous second argument so easily. (Just trying to work through this at the moment)

Thanks @aexmachina

**Comment by aexmachina** [comment]
Good to hear. Might be worth opening an issue on ember-cli?
