### ISSUE TITLE
Fixing SASS error doesn't reload the page from build error

### ISSUE THREAD

**Issue by SaladFork** [aexmachina/ember-cli-sass#135]
Recently the ability to have changed SASS styles hot-swapped without a reload was added (which is awesome!!).

A build error caused by invalid SASS, however, will cause the page to reload and display an error similar to:
> ### Build error
>
> **tmp/sass_compiler-input_base_path-SJwgbQCL.tmp/0/app/styles/_some-style.scss, line 96**
>
> **The Broccoli Plugin: [SassCompiler] failed with:**
>
> ---
> ```
> Error: Invalid CSS after "}": expected "}", was ""
>     at options.error (node_modules/node-sass/lib/index.js:272:32)
>
> The broccoli plugin was instantiated at: 
>     at SassCompiler.Plugin (node_modules/broccoli-plugin/index.js:7:31)
>     at SassCompiler.CachingWriter [as constructor] (node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:18:10)
>     at new SassCompiler (node_modules/broccoli-sass-source-maps/index.js:20:17)
> ```

Fixing this error triggers a hot-swap reload rather than a full page reload. This unfortunately means you are still on the build error page rather than viewing your application. You have to manually reload the page to get back to your application.

It would be great if instead of requiring a manual reload, fixing an error caused a full reload.

---

Using:
```
$ ember --version
ember-cli: 2.7.0
node: 6.3.1
os: darwin x64
$ npm ls --depth=0 | grep ember-cli-sass
├── ember-cli-sass@5.5.1
```

**Comment by aexmachina** [comment]
Thanks for reporting this. The reloading logic is provided by ember-cli, so this should be posted there.
