### ISSUE TITLE
addon usage instructions -- included should use `this`:

### ISSUE THREAD

**Issue by shaunc** [aexmachina/ember-cli-sass#138]
I believe in your documentation:
```
  included: function(app) {
    this._super.included(app);
  }
```
should be:
```
  included: function(/* app */) {
    this._super.included.apply(this, arguments);
  }
```

Using with ember-component-css, it causes a problem because expecting "this" to be the same.

**Comment by aexmachina** [comment]
Yes, that is true. Thanks.

**Comment by aexmachina** [comment]
It's very easy to suggest changes to a file using Github BTW. You just [view the file](https://github.com/aexmachina/ember-cli-sass/blob/master/README.md) and click the edit button. It'll create a fork and a PR for you. But that's cool I'll do it myself.

**Comment by shaunc** [comment]
Sure -- indeed I know. I guess I hesitate more to fork doc as what is "right" when explaining is more a matter of taste. But in this case -- a code sample -- that excuse doesn't seem to apply....

Anyway -- thanks for the package! :)
