### ISSUE TITLE
build uses cached, fingerprinted file when underlying image changes

### ISSUE THREAD

**Issue by blimmer** [aexmachina/ember-cli-sass#144]
I'm not sure if this is the right repo to note this in, but I'm experiencing a problem where I change an underlying image referenced in a sass file, but it does not change the fingerprinted output unless I make some other change to the file.

For instance:

```sass
// app.scss

.foo {
  background: url('foo.jpg');
}
```

Now if I update `foo.jpg` the fingerprint should change, but when I deploy, it does not produce a new sass file (I get the same fingerprinted version as I had before).

However, if I add **any** other rules to the scss file, it regenerates the fingerprint correctly.

```sass
// app.scss

body {
  color: brown;
}

.foo {
  background: url('foo.jpg');
}
```

I am seeing a `.sass-cache` in my node_modules, and there is one old version that hangs around **even after deleting node_modules**, which is where I'm assuming the bad fingerprint is coming from.

```bash
› ls -al node_modules/ember-cli-deploy/.sass-cache
total 0
drwxr-xr-x  7 blimmer staff 238 Dec  6 16:38 ./
drwxr-xr-x 24 blimmer staff 816 Dec  6 16:39 ../
drwxr-xr-x  5 blimmer staff 170 Dec  6 16:38 18b01df24ad85b260b73efc6b62f0b4b7fe3a5e9/
drwxr-xr-x  3 blimmer staff 102 Feb 26  2016 225853e73d86f76f22fdbadf752ff7592a401908/
drwxr-xr-x 10 blimmer staff 340 Dec  6 16:38 63bb2488d9c18695c4a4139200e5f79634793f9b/
drwxr-xr-x  5 blimmer staff 170 Dec  6 16:38 af7fa16f3b9f7108e83ee4c90fd7661c1d9e61de/
drwxr-xr-x 15 blimmer staff 510 Dec  6 16:39 afd564b478db421cb2b91ac51f4a4c08309a6620/
```

Any ideas on how to fix this? Is this the right place to file the bug?

**Comment by aexmachina** [comment]
Fingerprinting doesn't consider referenced files, just the content of the source files

**Comment by blimmer** [comment]
That seems like a bug or, at least unexpected behavior.

**Comment by blimmer** [comment]
This works with Javascript, it re-fingerprints the asset correctly so it seems broken that it doesn't work the same with sass builds. Is there a way to clear the cache in these cases?

**Comment by blimmer** [comment]
It seems like this issue might be the underlying issue: https://github.com/rickharrison/broccoli-asset-rev/issues/29

**Comment by aexmachina** [comment]
Right, I see what you're saying. Yes I agree. This module doesn't have anything to do with fingerprinting.
