### ISSUE TITLE
Error with 6.0.0

### ISSUE THREAD

**Issue by rwwagner90** [aexmachina/ember-cli-sass#149]
I'm seeing this: `'ember serve' terminated by signal SIGSEGV (Address boundary error)` Seems to clash with flexi somehow, as removing flexi seems to fix the problem. Perhaps because flexi depends on a 5.x version?

**Comment by aexmachina** [comment]
This is almost certainly a problem with node-sass. You can always use the previous version of ember-cli-sass. Feel free to reopen if necessary.

**Comment by rwwagner90** [comment]
@aexmachina I would assume this would cause a lot of issues as some people update addons and others do not. Seems if one dependency uses 5.x and one uses 6.x, it will blow up. I suppose there is no way around it though. Perhaps we should recommend people make `ember-cli-sass` a peerDependency and not lock the version or something?

**Comment by aexmachina** [comment]
@rwwagner90 I think the solution is easier - people should just use the version that works for them :) People can usually avoid upgrading if necessary.

**Comment by rwwagner90** [comment]
@aexmachina so how would you recommend going about that? Should it be a `peerDependency` to flexi or what? Unsure of the correct way to approach allowing whatever version the user wants.

**Comment by aexmachina** [comment]
If they're using an addon that requires v5 then they should use v5, and not
upgrade to v6. If they want to upgrade to v6 then contact the author of the
addon ​and ask them to upgrade to v6. In general this hasn't been a problem
for the many years that people have been using this addon.

**Comment by rwwagner90** [comment]
@aexmachina I suppose most people would have no problem upgrading to 6, but wouldn't it be possible to do a `peerDependency` or something and allow addons to work with whatever version the consuming app is using? If my addon works with 5.x and 6.x, I would assume a `peerDependency` of `>= 5.0` would just work with whatever version your app used.

**Comment by aexmachina** [comment]
I feel like we're discussing solutions to a problem that isn't really a problem - this has never happened before. `peerDependency` isn't a solution to this - it would require every user of this module, and any addon that uses it, to add `node-sass` to their package.json. And then it becomes their responsibility to keep this up to date and working with all their modules.
