### ISSUE TITLE
node-sass v4.4.0 unable to read files from bower_components

### ISSUE THREAD

**Issue by jrjohnson** [aexmachina/ember-cli-sass#153]
After v4.4.0 was released on Friday afternoon we started seeing:
`Error: File to import not found or unreadable: bower_components/font-awesome/scss/font-awesome` in our builds.  

Pinning to node-sass v4.3.0 seems to fix the problem.  I would guess that this is an issue with node-sass, but since I don't really have any understanding of the way these libraries work together I thought I should report it here first.

The full error message can be seen at:
https://travis-ci.org/ilios/calendar/jobs/196237897#L630

**Comment by aexmachina** [comment]
Yes, if changing the node-sass version fixes the problem then it'll be a node-sass issue.

**Comment by jrjohnson** [comment]
If anyone else is following along - I believe this is the result of https://github.com/sass/node-sass/issues/1876.  Path from project root are no longer being read automatically.
