### ISSUE TITLE
Ember Engines compatibility

### ISSUE THREAD

**Issue by KrisOlszewski** [aexmachina/ember-cli-sass#155]
Hi there! Thanks for an amazing Ember Addon. I've been playing with Ember Engines this week and trying to use Sass, for both host app and engine addons, but can't get it to work. Any guidance would be much appreciated. `app.scss` works like a charm, but `addon.scss` doesn't want to play.

**Comment by aexmachina** [comment]
I'm afraid that I'm not an authority on using `ember-cli-sass` inside an addon. I've done it, but haven't really pushed the boundaries of what's supported. I believe @dukex has some more experience with this than I, but I can't be sure. Good luck!

**Comment by dukex** [comment]
HI @KrisOlszewski, can you reproduce the problem in a public repo? 
We had some problems with `addon.scss` in the passed, the fix was done here https://github.com/aexmachina/ember-cli-sass/pull/78

**Comment by KrisOlszewski** [comment]
@dukex sure, I'll create a basic example tonight.

I'm running Ember CLI 2.11, then installed `ember-engines`, `ember-cli-sass`, and created couple of in-repo-addons. The expected result is to process `addon.scss` to `engine.css` which then is lazy loaded via host application based on mounted engine. Everything works when using `addon.css`, but fails with `.scss` extension.

**Comment by KrisOlszewski** [comment]
@aexmachina and @dukex looks like I figured it out. `ember-cli-sass` needs to be installed in application host, then referenced in in-repo-engine. Not sure why it didn't work at first, but fresh install resolved it. Thanks and my bad for opening an issue w/out fully debugging.

**Test App setup**
```
ember new test-app
ember install ember-engines ember-cli-sass
ember g in-repo-engine projects
mv app/styles/app.css app/styles/app.scss
touch lib/projects/addon/styles/addon.scss
```

**Add reference to `lib/projects/package.json`**
```json
{
  "dependencies": {
    "ember-cli-sass": "*"
  }
}
```
