### ISSUE TITLE
postcss, and scss side by side

### ISSUE THREAD

**Issue by brandonjmckay** [aexmachina/ember-cli-sass#157]
I'm trying to see if it's possible to process config files for my ui framework in scss, but have everything else be in postcss.
I'm thinking the way to do that would be to configure sass to _only_ watch the whitelisted files I want, and then have postcss import that.

I was trying to pass in options to prevent `ember-cli-sass` from trying to watch for `app.scss`, or `app-name.scss`.

I tried:

```
    sassOptions: {
      onlyIncluded: true,
      outputFile: 'legacy'
    },
```

But it still does `app.scss` automatically. 

Is there any way to configure this to do that? Or to make them live well side-by-side?
Thanks!

**Comment by brandonjmckay** [comment]
Hmmm... I just found [ember-cli-css-preprocess](https://github.com/n1ru4l/ember-cli-css-preprocess), which sounds like it's meant to address this.

I've now been able to get `scss` files, and `css` files living side-by-side but I can't seem to import the framework `scss` file I want to from my npm package. :(

Probably not your problem though.

**Comment by aexmachina** [comment]
Yeah I don't think that `node_modules` is available in the broccoli tree. I'm afraid this isn't something I have any experience with, good luck!
