### ISSUE TITLE
Trying to find correct structure to import variables in an addon

### ISSUE THREAD

**Issue by mickit** [aexmachina/ember-cli-sass#158]
I have a question and I cannot seem to find an answer.  My company has a private repository for an addon we developed.  We also have a scss directory and structure where we maintain for our scss variables in a `Themes` directory.  I am trying to `@import` the variable from its directory into our addon, then use the addon in an app.  
 
Main
----Themes
--------Vars.scss
----Repo
--------StoreFrontAddon
------------Addon
----------------Styles
--------------------Addon.scss

```css
@import "../../../Themes/Vars";

.required {
  color: $required;
}
.optionsGroup {
  width: 20%;
}
```
 
When I add the addon to an app, the relational reference breaks.  Shouldn’t `@import` “../../../Themes/Vars.scss” work in the addon or would I have to use scssOptions.  If scssOptions, how?  Can I set it relationally?  When I've add the addon to the app, i get `Error: File to import not found or unreadable: ../../../Themes/Vars`.
 
I appreciate any help you can give me.  I am relatively new to Ember and any help or references would be appreciated.
 
Thanks in advance for your help.

**Comment by aexmachina** [comment]
I wouldn't try to reach into the app from an addon, it's possibly not supported. I would use a different approach and import the addon from the app. You can probably use [this approach](https://github.com/aexmachina/ember-cli-sass#alternative-addon-usage).

**Comment by mickit** [comment]
Sorry, my explanation was a little off.  The css code shown is what is in `StoreFrontAddon/Addon/Styles/Addon.scss`.  So we are adding StoreFrontAddon to an app, but getting an error on the addon's css when we try to run the app.

**Comment by mickit** [comment]
Yes, it is a npm versioned and published addon and I do see it in `node_modules`.  The only thing that may not be typical is that my company maintains a private repository for our addons.  I am using a relational path in the `@import` statement in the addon's `styles/addon.scss` to supply styles colors, etc.

The way I understand it, `ember-cli-sass` compiles together the css in `StoreFrontAddon` and the `@import` file.  Then when `StoreFrontAddon` is added to my app, `Ember` compiles the `StoreFrontAddon` css and the app's `app.css` into `vendor.css`.  So if the `ember-cli-sass` resolves the css in the beginning, why would I getting an error in the app?  Maybe I am not understanding the process right.  Does this make sense?

**Comment by aexmachina** [comment]
Right, as I thought. So I'd refer you to my previous comment.

> I wouldn't try to reach into the app from an addon, it's possibly not supported. I would use a different approach and import the addon from the app...

Addons CSS gets compiled into vendor.css, and the app goes into `[name].css`. They'll probably be in separate trees so you probably can't import into the addon CSS from the app.
