### ISSUE TITLE
Re: Use Material Design Components with ember-cli-sass

### ISSUE THREAD

**Issue by MrChriZ** [aexmachina/ember-cli-sass#177]
I've created this post here on Stackoverflow:
https://stackoverflow.com/questions/48083865/use-material-design-components-with-ember-cli-sass/48085654#48085654

> 
> I'm trying to use Material Components Web(MDC-Web) with Ember-CLI-Sass. I've installed MDC-Web with Yarn
> 
> In my ember-cli-build.js file I've set my sass includePaths as so:
> 
>  sassOptions: {
>            includePaths: ['node_modules/material-components-web','node_modules/@material']      
>     }
> and then in my app.scss file attempted to import the full component library like so:
> 
> @import "material-components-web";
> However I'm getting the error:
> 
> Error: Error: File to import not found or unreadable: @material/button/mdc-button.
> 
> Why is the SASS compiler not finding it?

I think possibly I should have come here first - as I think it's probably an issue with my understanding of how to use the includePaths with ember-cli-sass.  Any guesses as to what I'm doing wrong?

**Comment by The-Don-Himself** [comment]
Hi @MrChriZ, you can close this issue since I've answered it on SO.
Cheers.

**Comment by MrChriZ** [comment]
Thanks Don.
