### ISSUE TITLE
Can't set includePaths for Bootstrap

### ISSUE THREAD

**Issue by maxkueng** [aexmachina/ember-cli-sass#18]
Hello

I'm trying to set the `includePaths` for bootstrap-sass-official but I can't seem to get it to work. I'm not sure what I'm doing wrong.

The Bootstrap SCSS files are in `bower_components/bootstrap-sass-official/assets/stylesheets`.

```
[max@terror ramsch-ember]$ ls -l bower_components/bootstrap-sass-official/assets/stylesheets
total 20
drwxr-xr-x 3 max users 4096 15.12.2014 02:15 bootstrap/
-rw-r--r-- 1 max users  141 12.11.2014 18:19 _bootstrap-compass.scss
-rw-r--r-- 1 max users  720 12.11.2014 18:19 _bootstrap-mincer.scss
-rw-r--r-- 1 max users 1316 12.11.2014 18:19 _bootstrap.scss
-rw-r--r-- 1 max users  131 12.11.2014 18:19 _bootstrap-sprockets.scss 
```

So I 've added the options as follows:

```javascript
var App = Ember.Application.extend({
  ...
  sassOptions: {
    includePaths: [
      'bower_components/bootstrap-sass-official/assets/stylesheets'
    ]
  }
});
```

And I try to include it in SCSS as follows:

```scss
@import "bootstrap/variables";
@import "bootstrap";
```

But that gives me an error in ember-cli:

```
Error: /home/max/projects/ramsch-ember/tmp/tree_merger-tmp_dest_dir-EHcg5Cac.tmp/app/styles/app.scss:3: file to import not found or unreadable: "bootstrap/variables"
```

If I remove `@import "bootstrap/variables";` the same happens with just `bootstrap`.

I have to include it using the full path in order to make it work:

```scss
@import "bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/variables";
@import "bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap";
```

So I'm assuming that there's a probem with `includePaths`.

Do you have an idea what I might be doing wrong?

**Comment by jpaas** [comment]
I'm having the same issue.
ember-cli = 1.5
ember = 1.9.1

**Comment by jpaas** [comment]
I had to add the following to my var ENV in config/environment.js:

```
    sassOptions: {
      includePaths: [
        'bower_components',
        'bower_components/bootstrap-sass-official/assets/stylesheets',
      ]
    },
```

**Comment by aexmachina** [comment]
Yes, the config is (incorrectly) in config/environment.js (much to my regret), as indicated in the README. This will be changed in a future version. @maxkueng pretty sure there's no problem here, but reopen the issue if you think there is.
