### ISSUE TITLE
Feature request: Environment switch

### ISSUE THREAD

**Issue by zyllorion** [aexmachina/ember-cli-sass#19]
```
@if compass-env()=='development' {
    @import "bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap";
}
```
That seems to be the common way in SCSS to add conditional logic, but currently doesn't appear to do anything.  Could you add a function (ember-env or just env?) to allow a different SCSS on each environment.

Thanks

**Comment by aexmachina** [comment]
It's not a need that I have, and I don't even know if it's possible to provide variables to libsass like that (via broccoli-sass and node-sass). Pull requests welcome though!
