### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by samselikoff** [aexmachina/ember-cli-sass#195]
Hi, I'm confused about which version to use & which are documented. The README seems to disagree with some of the notes on npm, and in the Releases page the latest version I see is 7.2, but I also have seen v8 and v9 thrown around?

Would be willing to help update the README if someone could clarify!

**Comment by archebyte** [comment]
I'm seeing this on npm outdated (note a downgrade?) Seems odd:
Package          Current  Wanted  Latest  Location
ember-ajax         3.1.0   3.1.1   3.1.1  
ember-cli-babel   6.17.0  6.17.2   7.1.2  
ember-cli-sass     9.0.0   9.0.0   8.0.1

**Comment by mileslane** [comment]
I am also curious about the move from sass to sassc.

**Comment by robclancy** [comment]
I tried out dart-sass and it was super slow compared to node-sass.

**Comment by Turbo87** [comment]
@aexmachina any comments on this?

**Comment by aexmachina** [comment]
The current version is v8.0.1. v9 was accidentally published and removed.

Yes, Dart sass is slower, but you can use node-sass if you so choose and there's instructions in the README about how to do this. We changed to Dart sass because the maintainer of that package submitted a PR to do so, and I chose to follow the upstream project.

**Comment by samselikoff** [comment]
@aexmachina thanks for the response. I don't see any v8 tags on GitHub, either in the repository or on the Releases tab. There's also no Changelog in the root of the project, so it's still hard to see what the current/latest version of the project is.

Would it be possible to tag each release of the v8.x series? Also, is it possible to remove v9 from npm, to avoid future confusion?

**Comment by aexmachina** [comment]
Have pushed the tags too (it's been a while since I was pushing regular updates and I've forgotten the gotchas!) I've deprecated the v9 version on npm as well.
