### ISSUE TITLE
v3.1.0-beta.4 includePaths not working

### ISSUE THREAD

**Issue by Globegitter** [aexmachina/ember-cli-sass#25]
I am running on `ember-cli 0.1.12` and just tried `3.1.0-beta4` and getting the error

```
File: project/tmp/tree_merger-tmp_dest_dir-Wf2Du1Zo.tmp/app/styles/_settings.scss (58)
file to import not found or unreadable: foundation/functions
Current dir: project/tmp/tree_merger-tmp_dest_dir-Wf2Du1Zo.tmp/app/styles/
```

If I go back to `3.1.0-beta` it works just fine.

**Comment by aexmachina** [comment]
You might be using the old configuration location. That should just work now. Have pushed a new version, can you confirm whether that's fixed it pls.

**Comment by Globegitter** [comment]
Working fine now - thanks.
