### ISSUE TITLE
unordered_map::at: key not found

### ISSUE THREAD

**Issue by MOPineyro** [aexmachina/ember-cli-sass#26]
Receiving the following error:
unordered_map::at: key not found

have the following in my environment.js:
 sassOptions: {
      includePaths: [
      'bower_components/neat/app/assets/stylesheets/',
      'bower_components/bourbon/app/assets/stylesheets/'
      ]
    }

**Comment by aexmachina** [comment]
This is going to be a libsass issue. Try using ember-cli-sass@3.1.0-beta.4

**Comment by MOPineyro** [comment]
went back to 3.10-beta and all is well.

**Comment by minimalweb** [comment]
If I revert back to beta 4, I end up with this error: https://github.com/aexmachina/ember-cli-sass/issues/24

**Comment by aexmachina** [comment]
That error (#24) should be fixed in v3.3.1 or 4.0.0-beta.5.
