### ISSUE TITLE
Can't specify multiple SASS files

### ISSUE THREAD

**Issue by paulcwatts** [aexmachina/ember-cli-sass#28]
With broccoli-sass and ember-cli 0.1.15, I am able to compile multiple SASS files using the `outputPaths` configuration as described here: http://www.ember-cli.com/#asset-compilation

When I replace broccoli-sass with ember-cli-sass, this no longer works. I created an example of this here: https://github.com/paulcwatts/multiple-sass

I have the configuration:

```javascript
var app = new EmberApp({
  outputPaths: {
    app: {
      css: {
        'app': '/assets/multiple.css',
        'b': '/assets/b.css'
      }
    }
  }
});
```

The master branch uses broccoli-sass, and the ember-cli-sass branch uses ember-cli-sass. If you build with master, you will only get two compiled CSS files: "multiple.css" and "b.css". However, in the ember-cli-sass branch, you only get "multiple-sass.css" files.

**Comment by aexmachina** [comment]
That's a reasonable feature request but I'm super busy this month, so I won't be able to do it until April I'm afraid. PRs are welcome though :)

**Comment by paulcwatts** [comment]
It's not pressing, since what I have works with broccoli-sass. However, I would like to be able to specify precision to the SASS compiler. Once I'm less of a broccoli newb I might try my hand at fixing this...

**Comment by aexmachina** [comment]
Okay good. You can already specify precision
<https://github.com/joliss/broccoli-sass#usage> using the .precision
option.​
​

**Comment by trentmwillis** [comment]
I believe I have found a way to fix this issue (was going to open an issue when I saw this). Will be putting up a pull request soon.

**Comment by trentmwillis** [comment]
@paulcwatts you should be good to go now!

**Comment by paulcwatts** [comment]
Thank you @trentmwillis!
