### ISSUE TITLE
vendor.css and app.css?

### ISSUE THREAD

**Issue by jmurphyau** [aexmachina/ember-cli-sass#29]
I’m using your plugin and had a question - is there a way to produce app.css and vendor.css?

For example I want to put all the bootstrap scss into vendor.css and my app scss into app.scss...

**Comment by aexmachina** [comment]
The simple answer is no. But the more complex answer is yes :)

vendor.css is created by ember-cli, so you'd need to integrate with its internal broccoli trees to do it. 

Probably the easiest way is to create an addon that compiles the SCSS and the adds the compiled CSS to the vendor.css using `app.import()`, but there might be challenges in this.

This is probably a question for ember-cli. Once we had a clear demonstration of how it could be achieved then I'd consider adding support for it to ember-cli-sass.
