### ISSUE TITLE
node-sass 3.0.0-pre is superceded by 3.0.0-alpha.1

### ISSUE THREAD

**Issue by elwayman02** [aexmachina/ember-cli-sass#34]
@aexmachina ember-cli-sass 3.2.1 depends on broccoli-sass-source-maps 0.6.2, which doesn't seem to exist (the only release/tags I see on that GitHub project are 0.6.0).  When I did an npm install on my project, 0.6.2 brought in node-sass 3.0.0-pre.  I see that 0.6.0 depends on 3.0.0-alpha.0, which is also not the latest version of node-sass.  I would gladly update broccoli-sass-source-maps to depend on 3.0.0-alpha.1, but I'm confused by the lack of a 0.6.2 tag anywhere on the project.  Did it get deleted?  If so, why is ember-cli-sass dependent on a non-existent version tag?

**Comment by aexmachina** [comment]
v0.6.2 certainly [does exist on npm](https://www.npmjs.com/package/broccoli-sass-source-maps), for some reason the code just hadn't been pushed to Github, and it does depend on node-sass@3.0.0-pre.

I've just updated to node-sass@3.0.0-beta.2 and pushed v0.6.3.

**Comment by elwayman02** [comment]
Fantastic, thanks!
