### ISSUE TITLE
Errors compiling bootstrap-sass-official

### ISSUE THREAD

**Issue by zyllorion** [aexmachina/ember-cli-sass#37]
ember-cli 2.2.2
ember 1.12 b1

```
Build failed.
File: bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_forms.scss (189)
You may not @extend an outer selector from within @media.
You may only @extend selectors within the same directive.
From "@extend .input-sm" on line 48 of bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_input-groups.scss
```

Works if I switch to `"broccoli-sass": "git://github.com/ef4/broccoli-sass"` but this doesnt have a sourceMap option.

**Comment by charlatan154** [comment]
i have the same issue with bootstrap-sass. I also confirm that it works if i switch to `"broccoli-sass": "git://github.com/ef4/broccoli-sass"`.

**Comment by jpaas** [comment]
I had this error also. But somehow it has now morphed into a node "Bus error: 10" every time I try to run ember.

**Comment by jpaas** [comment]
I tried going back to 3.0, but it seems to have errors in some script.
3.1.0 works for me.

**Comment by AW-UC** [comment]
This is caused by https://github.com/sass/node-sass/issues/823. Now node-sass has to be updated: https://github.com/sass/node-sass/issues/823
After that ember-cli-sass need to include the updated node-sass.

**Comment by seriousben** [comment]
@aexmachina Could we have broccoli-sass-source-maps as a peerDependencies? That would allow us to control the version of node-sass? What are your thoughts?

**Comment by aexmachina** [comment]
See [my comment](https://github.com/sass/node-sass/issues/823#issuecomment-88349142) on issue #823.

This module is really a very slight fork of broccoli-sass, so I don't want to diverge from its semantics unless absolutely necessary.

**Comment by searls** [comment]
I'm a new user of the addon and I'm getting "Bus Error 10" as well, even when I set `sourceMaps: false`. I'm a bit confused between the interplay between `broccoli-sass-source-maps` dependency on `node-sass` and the apparent peer dependency of this plugin on the `sass` module (which I can't find documentation for).

Is there a version of this plugin that'll work for new installs? Or do I need to fork and fix the transitive node-sass dependency to what I need?

**Comment by searls** [comment]
Belay my issue above, once I moved to 3.3.1 the problem is indeed fixed

**Comment by eduardocnegrao** [comment]
It is a shit!
