### ISSUE TITLE
Problem using bootstrap-sass & ember-cli-sass

### ISSUE THREAD

**Issue by justtal** [aexmachina/ember-cli-sass#38]
Hey,

If some of you getting error using bootstrap-sass, it's a problem in node-sass / sasslib.

You can use ember-cli-sass@3.1.0 until the'll fix the problem.

Cheers.

**Comment by abhilashlr** [comment]
Is it the @import errors in input-group.scss and navs.scss you are referring to?

**Comment by justtal** [comment]
Nop, the file are _forms.scss & _input-groups.scss

**Comment by abhilashlr** [comment]
Yeah that's what I meant too. In your input-group.scss just comment out the @extend .input-sm in line 48 and the one after that. You would get another issue in navs.scss in 130 odd lines again. Commenting these 4 lines will compile it in current sass compiler. But you would miss out on the styling. 

Does 3.1 solve this issue?

**Comment by justtal** [comment]
Yes,

Commenting the extends won't help if you use those styles :)

Like I said, you can use ember-cli-sass@3.1.0 until the'll fix the problem.

**Comment by abhilashlr** [comment]
OK. Let me try that out

**Comment by abhilashlr** [comment]
No I still see the same issue. Btw, i have node-sass-3.0.0beta. Does that have something to do with the error?

**Comment by justtal** [comment]
Yep. I think that is the problem.

Y do you have both node-sass & ember-cli-sass in your primary node-packages?

**Comment by abhilashlr** [comment]
No, I meant the node-sass which is a dependency of the ember-cli-sass. The package.json on ember-cli-sass > broccoli-sass-source-maps uses "node-sass: 3.0.0.beta.2"

I tried overriding the version to check if 2.1 node-sass works fine, but the compilation never ends! ember keeps building for long time and the server never starts.

**Comment by justtal** [comment]
Don't change the package.json of broccoli-sass-source-maps.

Change the 'ember-cli-sass' to 3.1.0 and it should work.

**Comment by abhilashlr** [comment]
I was just trying to test the cause of the problem and not really changing the package of the dependencies. And using ember-cli-sass 2.0.3 makes it work. I guess it is due to the latest node-sass version. 2.0.3 uses older node-sass version. 

3.1.0 dint work.

**Comment by justtal** [comment]
Can you show me your package.json file?

**Comment by abhilashlr** [comment]
My mistake! Though added 3.1.0 the ember-cli-sass was installing 3.2.2 due to '^' usage in package.json.

3.1.0 version works! Thanks :)

**Comment by justtal** [comment]
That is what I taught :)

**Comment by aexmachina** [comment]
This is an issue with node-sass v3. They're pushing out betas pretty quick, so keep reinstalling ember-cli-sass to get the latest beta and see if that fixes the problem. If not then the issue should be created on node-sass because this and the other broccoli modules can't do anything about compile issues. Alternatively just use the previous version of ember-cli-sass, which uses node-sass v2.

**Comment by abhilashlr** [comment]
Thats what I thought !
