### ISSUE TITLE
Using sassOptions config property in EmberApp doesn't work

### ISSUE THREAD

**Issue by mattconstantine** [aexmachina/ember-cli-sass#39]
I have a new ember-cli 0.2.2 app. I've tried setting sassOptions in the EmberApp constructor like so: 

```javascript
var app = new EmberApp({
  sassOptions: {
    includePaths: [
      'app/styles/foo'
    ]
  }
});
```

The includePaths never make it into the SassCompiler. As best I can tell it's because ember-cli-sass's `setupPreprocessorRegistry` is called independently of `included`. So `this.app` is never set causing `sassOptions` to not pick up the app's options.

I'm aware this isn't the recommended way to define includePaths. I started debugging this because I'm developing an ember add-on that needs to add to the includePaths. I'm all ears if there's a better way to do that outside of modifying the host app's `app.options.sassOptions`.

In any case, it'd be great if ember-cli-sass can continue to support the old config style if only for compatibility.

**Comment by joebartels** [comment]
hitting the same issue. So far I've come to same reasoning as @mattconstantine

**Comment by aexmachina** [comment]
Yes, this is all quite unfortunate. This is why it's important to be super critical when people send you PRs :) I will change this to support both uses and update the docs to refer to the Brocfile.js usage. Just on holiday with my kids right now, so difficult to find the time. Should be in the next few days, although PRs are welcome!

**Comment by mattconstantine** [comment]
I'd be happy to provide a PR but I couldn't see a straightforward way to get the host's `EmberApp` instance within `setupPreprocessorRegistry(type, registry)`. Any tips?

**Comment by aexmachina** [comment]
I'd look in the Git history to see how it used to work.

**Comment by aexmachina** [comment]
Going in to sort this out now.

**Comment by stefanpenner** [comment]
@aexmachina it is solved by https://github.com/aexmachina/ember-cli-sass/pull/42
