### ISSUE TITLE
Upstream issue with node-sass and foundation components

### ISSUE THREAD

**Issue by wzrdtales** [aexmachina/ember-cli-sass#40]
The current beta5 of node-sass introduced some bugs together with the foundation scss. An issue on the upstream project is open.

This leads to the behavior, that ember-cli does not compile the sccs of foundation anymore, with the following error:

    File: bower_components/foundation/scss/foundation/components/_forms.scss (335) expected a variable name (e.g. $x) or ')' for the parameter list for url

To anyone else having this problem:
downgrade your node-sass version in the ember-cli-sass module to beta4 fixes this problem.

Upstream Issues:
https://github.com/sass/libsass/issues/1059
https://github.com/sass/node-sass/issues/840

**Comment by laantorchaweb** [comment]
I have the same problem, I updated ember-cli and my project to the last version of ember-cli and I got this problem.

**Comment by seriousben** [comment]
Is there a way to downgrade a sub-package without using a shrinkwrap file?

**Comment by blisst** [comment]
+1 to @seriousben on ways to downgrade the sub-package.

For anyone like me who had trouble with this, to fix this error you actually have to go into 
`node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/package.json` and change the `node-sass` dependency to 3.0.0-beta.4.

**Comment by aexmachina** [comment]
Downgrading to ember-cli-sass@3.0.x should also fix this problem (there's obviously issues with the node-sass beta).

**Comment by aexmachina** [comment]
See #44 for details on this issue.

**Comment by aexmachina** [comment]
I've also published ember-cli@4.0.0-beta.4 which fixes the version of node-sass to 3.0.0-beta.4 to avoid this issue with Foundation. I'll publish another version when this issue is resolved.

**Comment by wzrdtales** [comment]
The current master branches of the upstream projects have the bugs fixed, but don't know when they want to release the new version. But anyway @aexmachina sticking to a specific version while a beta is so far the best one can and should do. If you publish the new version I suggest you also stick to the new release and not including the new ones already. While a running beta we have to expect, that things like this happen.

**Comment by aexmachina** [comment]
So, does beta.4 not resolve your issue?

**Comment by wzrdtales** [comment]
@aexmachina never said this ;) as also pointed out in my initiual issue it does, I was talking about the future releases of node-sass/libsass

**Comment by laantorchaweb** [comment]
@aexmachina the beta.4 is working fine, thanks!

**Comment by aexmachina** [comment]
node-sass is now a peerDependency, so you specify which version of node-sass@3.x to use in your package.json file.

**Comment by wzrdtales** [comment]
@aexmachina the peer dependency is not correctly configured, there is also already an issue to this open.
https://github.com/aexmachina/ember-cli-sass/issues/46

**Comment by aexmachina** [comment]
@wzrdtales I'm not sure I understand what you're saying. See #44 for details on the resolution. Please reopen if you've still got an issue.

**Comment by aexmachina** [comment]
Yes @wzrdtales, that's been fixed now.
