### ISSUE TITLE
Issues with node-sass betas

### ISSUE THREAD

**Issue by aexmachina** [aexmachina/ember-cli-sass#44]
#40 and #43 are both a result of the node-sass@3.0.x-beta-x versions. I think that [broccoli-sass should have gone to v1.0.0-beta-x version](https://github.com/joliss/broccoli-sass/issues/61) when it was upgraded to node-sass v3, but this didn't happen (and so I followed suit with ember-cli and broccoli-sass-source-maps). I now think this was a mistake, because several users have had to deal with failing builds without explicitly asking for a new version (see #40 and #43).

Here's what I've done to sort this out:

- broccoli-sass-source-maps@0.7.0 has reverted back to node-sass@2.x
- broccoli-sass-source-maps@1.0.0-beta.1 uses node-sass@3.x
- ember-cli@3.3.0 now uses node-sass@2.x via broccoli-sass-source-maps@0.7.0 
- ember-cli@4.0.0-beta.1 uses node-sass@3.x via broccoli-sass-source-maps@1.0.0-beta.1

Please let me know if you're experiencing any issues with this. Hopefully this should allow people who want node-sass v3 to use the betas, and the rest of the world will just get a SASS compiler that works :)

**Comment by ZebraFlesh** [comment]
Thanks for making this change, it's much appreciated. It's soooo close, but not quite there. It looks like you didn't push new info about broccoli-sass-source-maps@0.7.0 to npm.  After `npm uninstall --save-dev ember-cli-sass; rm -rf node_modules; npm cache clean`, I tried `npm install --save-dev ember-cli-sass` and was greeted with:

````
No compatible version found: broccoli-sass-source-maps@'>=0.7.0 <0.8.0'
Valid install targets:
["0.6.2","0.6.3","1.0.0-beta.1","1.0.0-beta.4"]
````
And indeed doing an `npm view broccoli-sass-source-maps` yields:

````
{ name: 'broccoli-sass-source-maps',
  description: 'Libsass-based Sass compiler for Broccoli',
  'dist-tags': { latest: '1.0.0-beta.4' },
  versions: [ '0.6.2', '0.6.3', '1.0.0-beta.1', '1.0.0-beta.4' ],
  maintainers: 'aexmachina <simon.wade@gmail.com>',
  time: 
   { modified: '2015-04-09T07:06:55.349Z',
     created: '2015-03-17T03:56:18.520Z',
     '0.6.1': '2015-03-17T03:56:18.520Z',
     '0.6.2': '2015-03-17T04:10:42.897Z',
     '0.6.3': '2015-03-26T22:35:34.674Z',
     '1.0.0-beta.1': '2015-04-09T06:47:40.635Z',
     '1.0.0-beta.4': '2015-04-09T07:06:55.349Z' },
...
````

**Comment by aexmachina** [comment]
node-sass is now a peerDependency, so you specify which version of node-sass@3.x to use in your package.json file.

**Comment by aexmachina** [comment]
Thanks @ZebraFlesh, that's published now.

**Comment by ZebraFlesh** [comment]
Many thanks! Everything works great now and I'm back in a happy place: I've got a stable sass build including bourbon mixins to support my terribly old FF 10 users (don't ask). Life is good. :thumbsup::thumbsup:
