### ISSUE TITLE
No compatible version found: node-sass@'>=3.0.0 <4.0.0'

### ISSUE THREAD

**Issue by davewasmer** [aexmachina/ember-cli-sass#46]
Trying to install into a fresh project (using both `ember install` and `npm install`) results in:

```
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/Users/daw/.nvm/versions/node/v0.12.2/bin/npm" "install" "ember-cli-sass@4.0.0-beta.4"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.3
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: node-sass@'>=3.0.0 <4.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.9.4-rc1","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.3.0","0.4.0","0.4.1","0.4.2","0.4.3","0.4.4","0.5.0","0.5.1","0.5.2","0.5.3","0.5.4","0.6.0","0.6.1","0.6.2","0.6.3","0.6.4","0.6.5","0.6.6","0.6.7","0.7.0-alpha","0.7.0","0.8.0","0.8.1","0.8.2","0.8.3","0.8.4","0.8.5","0.8.6","0.9.0","0.9.1","0.9.2","0.9.3","0.9.4-rc1","0.9.4","0.9.5-rc1","0.9.5","0.9.6","1.0.0","1.0.1","1.0.2-alpha","1.0.2","1.0.3","1.1.0","1.1.1","1.1.2","1.1.3","1.1.4","1.2.0","1.2.1","1.2.2","1.2.3","2.0.0-beta","2.0.0","2.0.1","3.0.0-alpha.0","3.0.0-beta.2","3.0.0-beta.3","3.0.0-beta.4","2.1.0","2.1.1","3.0.0-beta.5"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'ember-cli-sass'
npm ERR! notarget
```

Looking at [node-sass](https://www.npmjs.com/package/node-sass), it looks like 2.1.1 is the latest release, but this package depends on broccoli-sass-source-maps, which depends on node-sass ^3.0.0 as a peer dependency.

Not sure how that's possible, perhaps node-sass unpublished a node package?

**Comment by alfv89** [comment]
I'm facing the same problem...

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: node-sass@'>=3.0.0 <4.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.9.4-rc1","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.3.0","0.4.0","0.4.1","0.4.2","0.4.3","0.4.4","0.5.0","0.5.1","0.5.2","0.5.3","0.5.4","0.6.0","0.6.1","0.6.2","0.6.3","0.6.4","0.6.5","0.6.6","0.6.7","0.7.0-alpha","0.7.0","0.8.0","0.8.1","0.8.2","0.8.3","0.8.4","0.8.5","0.8.6","0.9.0","0.9.1","0.9.2","0.9.3","0.9.4-rc1","0.9.4","0.9.5-rc1","0.9.5","0.9.6","1.0.0","1.0.1","1.0.2-alpha","1.0.2","1.0.3","1.1.0","1.1.1","1.1.2","1.1.3","1.1.4","1.2.0","1.2.1","1.2.2","1.2.3","2.0.0-beta","2.0.0","2.0.1","3.0.0-alpha.0","3.0.0-beta.2","3.0.0-beta.3","3.0.0-beta.4","2.1.0","2.1.1","3.0.0-beta.5"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by ivanoats** [comment]
The PeerDependency here does not work because node-sass 3 is still in beta?
https://github.com/aexmachina/broccoli-sass-source-maps/blob/master/package.json#L27

**Comment by davewasmer** [comment]
@ivanoats that's what it seems like. I just wasn't sure if broccoli-sass-source-maps was published requiring a version of node-sass that doesn't seem to exist, or if it did exist, and perhaps the node-sass project had to unpublish that version somehow.

@aexmachina happy to submit a PR updating the reference to the beta tag, if that's helpful / easier.

**Comment by zyllorion** [comment]
+1

**Comment by nielsen** [comment]
+1

**Comment by shime** [comment]
+1

**Comment by joeczucha** [comment]
+1 (is there a workaround for this?)

**Comment by alexdiliberto** [comment]
+1

**Comment by dylanfoster** [comment]
Since the dependency here is `^broccoli-sass-source-maps@1.0.0-beta.4` it picks up the latest of that range which is now `broccoli-sass-source-maps@1.0.0-beta.5` which introduced `node-sass@^3.0.0` as a peerDependency which doesn't exist yet. You can `npm install --save-dev broccoli-sass-source-maps@1.0.0-beta.4` to override `ember-cli-sass's` dependency on it as a workaround.

There's a [PR](https://github.com/aexmachina/broccoli-sass-source-maps/pull/2) for the fix in `broccoli-sass-source-maps`

**Comment by BrianBravo** [comment]
+1

**Comment by chrism** [comment]
+1

**Comment by underoot** [comment]
+1

**Comment by aexmachina** [comment]
This should be resolved now.

**Comment by chrism** [comment]
works great for me, thanks :+1:
