### ISSUE TITLE
@importing ruby packages into .scss files

### ISSUE THREAD

**Issue by mooror** [aexmachina/ember-cli-sass#51]
Hey there I was wondering, how do I import something like susy (http://susy.oddbird.net/) into the scss. It is installed using gem install susy. I used to be able place @import "susy"; in my scss code and it would import the ruby package. I mean I have been able to load bower scss partials in just fine but not ruby packages.

**Comment by aexmachina** [comment]
You will need to get the files into your broccoli tree, and then you can make them available in the SASS using `includePaths`. 

You could add an absolute path to `includePaths`, but I wouldn't recommend that.

My suggestion would be to find a way to add them to your project - maybe they're available as a bower/npm package, or simply copy them in. This is one of the problems with the RubyGems model - they're external to your package.
