### ISSUE TITLE
How should we configure this plugin?

### ISSUE THREAD

**Issue by toranb** [aexmachina/ember-cli-sass#55]
I realize the README says to configure this addon using the Brocfile like so ...

```js
var app = new EmberApp({
  outputPaths: {
    app: {
      css: {
        'app': '/assets/application-name.css',
        'themes/alpha': '/assets/themes/alpha.css'
      }
    }
  }
});
```

But most of my modern ember-cli apps use the config/environment file instead like so

```js

module.exports = function(environment) {
  var ENV = {
  //tons of other configuration ...

  ENV.sassOptions = {
      includePaths: [
          'bower_components/foundation/scss',
          'app/styles'
      ]
  };

  return ENV;
};
```

How should we configure using this to build a single app.css / and if I'm using the config example ... how should I configure it to output both app.css and another file (at the same time) ?

**Comment by aexmachina** [comment]
Configuration in the config/environment file is for the client-side, and the SASS config is entirely server-side, so it belongs in the Brocfile.

There's information [in the README](https://github.com/aexmachina/ember-cli-sass#processing-multiple-files) about creating multiple files.

Please feel free to reopen the issue if anything is not clear.
