### ISSUE TITLE
can't install in new project

### ISSUE THREAD

**Issue by yonida** [aexmachina/ember-cli-sass#58]
Getting this:
npm install ember-cli-sass --save-dev
npm ERR! fetch failed https://registry.npmjs.org/center-align/-/center-align-0.1.1.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org
npm ERR! fetch failed https://registry.npmjs.org/async/-/async-1.2.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT
...
npm keeps spinning forever.. is it just me?

**Comment by aexmachina** [comment]
Yup, just you. It doesn't use that package.
