### ISSUE TITLE
What is the difference between this package and broccoli-sass?

### ISSUE THREAD

**Issue by Restuta** [aexmachina/ember-cli-sass#59]
As an Ember and Ember-cli user I am a little bit lost how these two packages are different. We used to use https://www.npmjs.com/package/broccoli-sass, but now we came over this addon and I am wondering what are use-cases to use one or another? 

I see both of them use node-sass internally. Thanks in advance.

**Comment by aexmachina** [comment]
ember-cli-sass provides the common use case for use with ember-cli. It's the recommended solution for using libsass in an ember-cli project.

Basically it provides the following defaults:

- Source maps in development
- Handles the [`outputPaths` configuration](http://www.ember-cli.com/#configuring-output-paths)
- Detects whether to use `.scss` or `.sass` file extensions
