### ISSUE TITLE
Brocfile.js outputPaths CSS ignored

### ISSUE THREAD

**Issue by pedropaf** [aexmachina/ember-cli-sass#61]
I'm setting the path in outputPaths as specified in the docs, it was working fine for everything when I was using css, but since I installed foundation-sass and sass compiler, now that parameter is being ignored, and my compiled app.scss is going to /assets/app-name.css Any ideas on how to fix this? Thanks!

**Comment by aexmachina** [comment]
It looks very much like an issue with foundation-sass. Also it's not clear what you mean by "sass compiler". I'd suggest you post this issue on foundation-sass.
