### ISSUE TITLE
Upgrade upstream broccoli-sass-source-maps node-sass dep

### ISSUE THREAD

**Issue by blimmer** [aexmachina/ember-cli-sass#62]
There's no ability to add this to [the repo](https://github.com/aexmachina/broccoli-sass-source-maps) so I'll file here. Broccoli-sass-source-maps relies on [node-sass ^3.1.0](https://github.com/aexmachina/broccoli-sass-source-maps/blob/master/package.json#L23) and 3.2.0 [was released](https://github.com/sass/node-sass/releases/tag/v3.2.0) about a month ago. 

Can we bump that to `^3.2.0`?

**Comment by deepflame** [comment]
:+1:

**Comment by aexmachina** [comment]
I've pushed an update to master, can someone please test for me? I'm don't have any up-to-date Ember.js projects to test on right now. Thanks for pointing out that issues were disabled, that's been fixed.

**Comment by aexmachina** [comment]
All the tests are passing on release, beta and canary so I've published v4.0.0. Let me know if there's any issues.

**Comment by aexmachina** [comment]
x

**Comment by blimmer** [comment]
The only change I see is to the README.md [from 4.0.1 to master](https://github.com/aexmachina/ember-cli-sass/compare/v4.0.1...master). What, specifically, do you want us to test? I have several Ember apps I'd be willing to test on.

**Comment by aexmachina** [comment]
Yes, thanks. I've fixed and pushed v4.1.0.
