### ISSUE TITLE
Compile is very slow - only compile when styles change

### ISSUE THREAD

**Issue by blimmer** [aexmachina/ember-cli-sass#63]
I don't know if there's anything we can do in this addon, but my build is extremely slow for building sass:

Right now, my sass builds takes > 20 seconds on each save. It would be nice to only incur that delay when I change styles. I think the biggest thing is that we recompile all the sass anytime any of the files change. Is there a way to only rebuild when something in `app/styles` changes?

Cold Build:
```
Build successful - 51632ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
SassCompiler                                  | 20416ms
Babel                                         | 7292ms
Babel                                         | 4652ms
CoffeeScriptFilter                            | 2922ms
ES6: App Tree                                 | 2773ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
SassCompiler (1)                              | 20416ms
Babel (8)                                     | 12836ms (1604 ms)
CoffeeScriptFilter (2)                        | 4721ms (2360 ms)
ES6: App Tree (1)                             | 2773ms
```

Subsequent:
```
file changed adapters/customer.coffee

Build successful - 25769ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
SassCompiler                                  | 20473ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
SassCompiler (1)                              | 20473ms
```

**Comment by blimmer** [comment]
For those having this problem - it turned out to be our uses of `@extend`. When we removed those, our sass build went down to ~5 seconds. I still think it would be useful to only run this build on sass file changes, but it sounds like we might be waiting on upstream broccoli changes.

**Comment by microcipcip** [comment]
How many `@extend` did you use to get such a slow compilation time?

**Comment by aexmachina** [comment]
@stefanpenner has some performance improvements incoming once ember-cli provides some new features that enable it.
