### ISSUE TITLE
Does not respect alternate inputPath for styles directory

### ISSUE THREAD

**Issue by bcardarella** [aexmachina/ember-cli-sass#64]
When instantiating `EmberApp` we can change the location of the styles directory. A client application shares styles between multiple ember apps with the following structure:

```
└── app_1
├── app_2
├── app_3
└── dependencies
    ├── styles
```

so in each `App` we declare the styles tree to be:

```js
new EmberApp({
  trees: {
    styles: '../dependencies/styles'
  }
});
```

This was just fine with a combination of Ember 1.10, ember-cli 0.2, and embrer-cli-sass 2.0.x.

Upgrading everything is broken. My research has shown that ember-cli-sass is trying to verify the existence of style files in `./app/styles` regardless of the style tree location override: https://github.com/aexmachina/ember-cli-sass/blob/master/index.js#L36

higher up the food chain ember-cli will Funnel all style trees for the app into `app/styles` to normalize how everything acts upon it. This would be fine but ember-cli-sass is checking for the existance of this path from the cwd of the project rather than within the tree that is passed in.

At the point of execution that these checks are done the tree has not been run and so there is no directory yet. I realize that this check is done for performance reasons but I would advocate to move this check into the lower level of the Broccoli handling and wait for the tree to be available to act up to check for the existence of files to be acted upon.

If this is agreeable I can write up a PR.

**Comment by aexmachina** [comment]
Yes, that was exactly my concern when I received the PR that added that check. TBH I'd prefer to remove it alltogether, and require people to specify the `extension` option if they want to use a `.sass` file as an entry point.

I'd be happy to accept a PR which either removed this check or changed it to work on the supplied Broccoli tree.

On another note, I've just started as CTO of a mobile development company and I'm not using my Ember packages and I'm just not finding the time to maintain them. I know you have good connections in the community, so I wanted to ask you if you or anyone you know would be interested in becoming a collaborator on this project? I know that it's a pretty important piece of the ember-cli ecosystem now, so I want to make that it's being well maintained.

**Comment by bcardarella** [comment]
Looks like https://github.com/aexmachina/ember-cli-sass/blob/master/index.js#L22 allows me to work around this for now.

I can ask the ember-cli-core team room if anyone wants to adopt. I believe this is a default ember-cli addon for ember-cli and for that reason it shouldn't go stale. At the very lease someone should get github merge/npm push rights

**Comment by aexmachina** [comment]
Yes that's true. Okay great thanks! Yes I agree it's important.
