### ISSUE TITLE
Requires restarting `ember server`

### ISSUE THREAD

**Issue by stickwithjosh** [aexmachina/ember-cli-sass#69]
Just had a few confusing minutes as a result of having the server already running. Restarting (not reload, the server reloads when the files change without the css being generated) is the only thing required to fix, but without restarting the SASS / SCSS never gets compiled.

Maybe just noting this in the README is good enough? Not even sure how much of that is available

**Comment by aexmachina** [comment]
That's certainly not the usual behaviour. I think it's unlikely that's caused by this module, probably another issue I'd say.

**Comment by aexmachina** [comment]
I've just confirmed that it is indeed reloading the CSS for me.

**Comment by pogopaule** [comment]
@stickwithjosh I experience a similar issue. The css gets build once after `ember serve`. Changes to a SASS file are recognised by ember-cli, and a rebuild is triggered. But actually the new css is not generated...The only thing that helps is to restart the server :(

**Comment by aexmachina** [comment]
Can I ask whether you're putting the `.scss` files into `styles/` or into a pod folder?
