### ISSUE TITLE
.idea folder in 'ember-cli-sass' dir in node_modules

### ISSUE THREAD

**Issue by gregzx** [aexmachina/ember-cli-sass#77]
Intelij .idea folder makes its way into the addon folder in node_modules after executing 'ember install ember-cli-sass' command. I think '.idea' should be added to .gitignore file.

<img width="151" alt="idea" src="https://cloud.githubusercontent.com/assets/9517223/10124355/77110c62-6553-11e5-8909-900bff0ad35f.png">

Cheers,

**Comment by aexmachina** [comment]
Ah good, thanks. That's fixed in v4.2.1.
