### ISSUE TITLE
Readme claims that plugin detects when to use sass vs scss, didn't work

### ISSUE THREAD

**Issue by smackesey** [aexmachina/ember-cli-sass#80]
- I started a new project with ember-cli: `ember new myproject`
- I installed ember-cli-sass: `ember install ember-cli-sass`
- I created my app.sass file in app/styles
- Broccoli build error: **File not found: /app/styles/app.scss**
- Thought maybe it was the empty but auto-generated /app/styles/app.css causing this issue, so I deleted it. Still got the same Broccoli error.

I was able to compile by settings the `extension` option in ember-cli-build.js, but the README implies that I should just be able to use **.sass** extensions with no configuration.

**Comment by aexmachina** [comment]
Yes, you need to specify the `extension` option in v5 if you're not using `.scss`. I've updated the README.
