### ISSUE TITLE
5.0.0 now requires `app.scss` to be present?

### ISSUE THREAD

**Issue by grantovich** [aexmachina/ember-cli-sass#81]
I have an app with multiple themes, which I accomplish like this in my `ember-cli-build.js`:

```js
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    outputPaths: {
      app: {
        css: {
          'theme-one': '/assets/theme-one.css',
          'theme-two': '/assets/theme-two.css'
        }
      }
    }
  });

  return app.toTree();
};
```

Then I have `app/styles/theme-one.scss` and `app/styles/theme-two.scss`, both of which define a bunch of variables and then `@import` a "master" stylesheet, which in turn imports the rest.

This worked fine in `ember-cli-sass` version 4.2.1. When upgrading to 5.0.0, without any other changes, the build now fails with this message:

```
Error: File not found: /app/styles/app.scss
in any of the following include paths:
  /.../tmp/sass_compiler-input_base_path-4CJuudV1.tmp/0
    at Object.findFileSync (/.../node_modules/include-path-searcher/index.js:12:9)
    at SassCompiler.build (/.../node_modules/broccoli-sass-source-maps/index.js:59:31)
    at /.../node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:142:21
    at lib$rsvp$$internal$$tryCatch (/.../node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/.../node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/.../node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/.../node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

The error message is completely correct in that I do not have an `app.scss` file, but I didn't need one before and I'm not sure why I would want one now. Is it intentional that this is now required? I'm not seeing a CHANGELOG or HISTORY or anything like that around.

**Comment by aexmachina** [comment]
@dukex any ideas on why this would be broken in v5?

**Comment by dukex** [comment]
Thanks @grantovich I can confirm this bug

@aexmachina I investigated the issue and found a code in the ember-cli ([ember-app.js#L183-L185](https://github.com/ember-cli/ember-cli/blob/4ead2f18e58dc61502ab8cabf90f28c3de7a8ae2/lib/broccoli/ember-app.js#L183-L185)) that puts the app to outputhPaths, the ember-cli-sass always receive the paths like that:

```
> paths
{ 'theme-one': '/assets/theme-one.css',
  app: '/assets/myapp.css' }
```

I believe the ember-cli should send the correct outputPaths, but if it is expected and addon need handle it, I can try to fix it

**Comment by aexmachina** [comment]
The question is why/did it used to work and what has changed.

**Comment by dukex** [comment]
@aexmachina This problems isn't new, on the 4.2.1 if you specify the sass extension and use `outputPaths` without 'app' you'll got the same error. 

old code:
````  js
   input = tryFile(....)
   ....
   if (input) {
      trees.push(new SassCompiler(inputTrees, input, output, options));
   }
```

Without the `tryFile` function the `input` never will be false.  The error is evident on 5.0.0 because I remove the `tryFile`.

**Comment by aexmachina** [comment]
@grantovich it looks to me from the ember-cli code (see @dukex's comment) that you might be able to resolve this by setting `outputPaths.app.css.app` to `null`. Can you confirm?

**Comment by grantovich** [comment]
@aexmachina Unfortunately that gives me a different error:

```
TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:477:5)
    at SassCompiler.build (/.../node_modules/broccoli-sass-source-maps/index.js:49:23)
    at /.../node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:142:21
```

Tried the empty string also, it just gave the same error as I got originally.

**Comment by aexmachina** [comment]
Yeah @dukex if you have any ideas on a solution that would be appreciated. I'm not using Ember at the moment, so really relying on contributors like yourself for things like this.

**Comment by dukex** [comment]
@aexmachina the easy way is put a ```try...catch``` in [broccoli-sass-source-maps#L59](https://github.com/aexmachina/broccoli-sass-source-maps/blob/master/index.js#L59), but I believe the ember-cli should not send the `app` key in outputPath when not configured.

**Comment by aexmachina** [comment]
No, I don't want to gobble the error - it's important that that exception is provided to the caller. I agree that (once again) the issue should be handled in ember-cli. @grantovich, pending a response to ember-cli/ember-cli#4948, I think you should just work around the issue by creating an empty app.scss file?

**Comment by grantovich** [comment]
So far I am successfully working around the issue by not upgrading to 5.0.0, since so far this internal change is the only new thing from 4.2.1 :smile: So it's not a huge thing. Thanks @dukex for submitting the Ember-CLI issue.

**Comment by lolmaus** [comment]
Ran into this too. Staying on 4.2.1 as @grantovich suggested.

**Comment by SirZach** [comment]
I'm getting complaints about  `app.[scss|sass]` not existing but yet I have a `app/styles/app.scss`. Any thoughts?

**Comment by dukex** [comment]
@SirZach Can you reproduce this error in a public repository to me investigate?

**Comment by dukex** [comment]
@grantovich You can create a empty app.scss and I believe will works fine with ember-cli-sass >= 5

**Comment by SirZach** [comment]
@dukex https://github.com/SirZach/bbbbbbbbbbbbbbb/tree/ember-cli-update is the repo and the branch is `ember-cli-update`

**Comment by grantovich** [comment]
Thanks @dukex, I was aware of this workaround courtesy of [@aexmachina's comment](https://github.com/aexmachina/ember-cli-sass/issues/81#issuecomment-147569774). Nice work with the pull request to Ember CLI :+1:

**Comment by digitalbreed** [comment]
@SirZach running into the same issue, did you find a solution by any chance?

**Comment by SirZach** [comment]
@digitalbreed I happened to also have `broccoli-sass` installed which was causing the problem

**Comment by datasc123** [comment]
I am running into same issue, creating empty app.scss file does not help eventually.

**Comment by stephencarr** [comment]
Even with `app.scss` present I am getting a problem:

```
The Broccoli Plugin: [SassCompiler] failed with:
Error: File not found: /app/styles/app.scss
in any of the following include paths:
  /route/to/my-app/tmp/sass_compiler-input_base_path-i26LVP4z.tmp
```

**Comment by lolmaus** [comment]
@stephencarr Which version? Can you make the source of your app available on GitHub?

**Comment by stephencarr** [comment]
Version `6.0.0`, maybe I should try 5? I can't really share it as it's in a private repo.

**Comment by lolmaus** [comment]
`6.0.0` has been published less than 24 hours ago and in't even tagged on GitHub. It might contain a regression?

@stephencarr Please reproduce the issue in a clean Ember CLI 2.10.0 boilerplate and report in a new thread.

**Comment by stephencarr** [comment]
Found the problem: https://github.com/aexmachina/ember-cli-sass/issues/147
