### ISSUE TITLE
Performance slowdown in SassCompiler when switching from npm 2 to npm 3 on Windows

### ISSUE THREAD

**Issue by adam-knights** [aexmachina/ember-cli-sass#85]
I gave node v4 and npm v3.3.9 a go for the first time today (had previously been using v0.12.7 and 2.11.x), my rebuild times (on windows 7) have near tripled to 48s from 20s. Rebuild output is below.

```
Build successful - 48766ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
SassCompiler                                  | 17852ms
BroccoliMergeTrees                            | 4836ms
TreeMerger (vendor)                           | 4362ms
Funnel: App JS Files                          | 3636ms
ES6: App Tree                                 | 2544ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
SassCompiler (1)                              | 17852ms
BroccoliMergeTrees (4)                        | 5059ms (1264 ms)
TreeMerger (vendor) (1)                       | 4362ms
Funnel: App JS Files (1)                      | 3636ms
ES6: App Tree (1)                             | 2544ms
```

Previously I was seeing a rebuild more like this with npm2:

```
Build successful - 20183ms.

Slowest Trees                                 | Total
----------------------------------------------+-------------------
Funnel: App JS Files                          | 2506ms
ES6: App Tree                                 | 2110ms
TreeMerger (vendor)                           | 1949ms
BroccoliMergeTrees                            | 1612ms
ConcatWithMaps                                | 1610ms
SassCompiler                                  | 1326ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+-------------------
Funnel: App JS Files (1)                      | 2506ms
ES6: App Tree (1)                             | 2110ms
ConcatWithMaps (4)                            | 2087ms (521 ms)
TreeMerger (vendor) (1)                       | 1949ms
BroccoliMergeTrees (4)                        | 1782ms (445 ms)
TreeMerger (lint) (2)                         | 1341ms (670 ms)
SassCompiler (1)                              | 1326ms
Babel (8)                                     | 1087ms (135 ms)
```

So the biggest offender appears to be the sass compiler.

I posted an example app for a different issue but this shows our sass layout and dependencies etc: https://github.com/adam-knights/order-example-oct-2015

ember-cli-sass 5.0.0, ember cli 1.13.8

I'm assuming this is a ember-cli-sass issue, but can post against ember-cli if thats the offender here.

**Comment by adam-knights** [comment]
Also tried ember cli from it's master branch, still similarly slow sasscompiler:

```
Build successful - 74514ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
SassCompiler                                  | 23309ms
TreeMerger (appAndDependencies)               | 4690ms
TreeMerger (vendor)                           | 4470ms
TreeMerger (appJS  & processedEmberCLITree)   | 4440ms
Addon#treeFor (Ember CLI ic-ajax - vendor)    | 3822ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
SassCompiler (1)                              | 23309ms
Babel (12)                                    | 12088ms (1007 ms)
TreeMerger (appAndDependencies) (1)           | 4690ms
TreeMerger (vendor) (1)                       | 4470ms
TreeMerger (appJS  & processedEmberCLI... (1) | 4440ms
Addon#treeFor (Ember CLI ic-ajax - ven... (1) | 3822ms
```

**Comment by adam-knights** [comment]
To confirm, leaving node at 0.12.7 but increasing npm to  v3.3.9 shows the issue is caused by npm from v2 to v3.

**Comment by aexmachina** [comment]
Hmmn, that is very strange. Are you doing a clean install when you change versions of npm and node (by deleting `node_modules/`)?

**Comment by stefanpenner** [comment]
this is because ember-cli-sass and friends are somewhat overoptimistic in what paths they watch, as npm v3 dedupes, its more likely all of node_modules gets watched by mistake.

Long term, better utilization of watchman will prevent this (I'm waiting on them finishing some stuff for us, and for us to more fully embrace the fs-tree-diff stuff). Short term, removing all the input-watch paths (maybe opt-in) would improve this.

^^ is likely something we will want to pursue from ember-cli side, but its all quite intertwined.

**Comment by adam-knights** [comment]
Yes, in trying each combo I always ran rmdir /s /q node_modules bower_components dist tmp and then did new npm install/bower install's.

**Comment by tsing80** [comment]
Update broccoli-sass-source-maps to disable caching as in tsing80/broccoli-sass-source-maps@a066c9ad50345c8114fe6b9a6049cafcca2c648f have big boost for me, not sure if it work for others though

**Comment by stefanpenner** [comment]
Yup it likely would. Since the way to derive the cache key is currently must check for changes literally everywhere.

**Comment by stefanpenner** [comment]
I believe the issue was, some addon,s like ember-cli-ic-ajax, accidentally inluded large chunks of node_modules (all of them) by mistake due to v3 deduping. 

If the problem arises again, please provide a reproduction and i will glady dig into it and address.

**Comment by adam-knights** [comment]
I tried node 4 and npm 3 again with latest Ember CLI and rebuild times are now the best we've ever had, ~3s with no SSD.
