### ISSUE TITLE
Build fails with "Expanded null selector" error

### ISSUE THREAD

**Issue by amageed** [aexmachina/ember-cli-sass#87]
I recently added ember-cli-sass and had Sass working fine on one machine. I cloned my repo on a different machine and ran into this issue. The code is the same, cloned directly from the repo.

When I run `ember build` I get:

```
version: 1.13.1
Build failed.
Expanded null selector
Error: Expanded null selector
    at options.error (/Users/amageed/code/emberproject/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/lib/index.js:277:32)
```

A blank `app.scss` file gives no error, but any CSS content causes this error to occur.

I'm not sure what could possibly be different between both machines and their setups. They're both running the same versions of node, and all dependencies are coming straight from what I had defined in package.json and bower.json. A co-worker was also able to clone the repo and had a successful build.

I'm on Node v0.12.7 (npm 2.11.3), ember-cli 1.13.1, ember 1.12.1.

I've tried completely removing node and associated folders, and reinstalling the dependencies from npm/bower to start fresh but there was no difference.

Any ideas?

**Comment by aexmachina** [comment]
This is almost certainly a node-sass issue. Have you removed the node_modules directory? I suggest you create an issue on node-sass.

**Comment by amageed** [comment]
Thanks @aexmachina, I'll try there. And yes, I tried removing node_modules and installing everything fresh, but got the same error.

**Comment by amageed** [comment]
@aexmachina BTW, when I install node-sass via npm and run it directly against my Sass files, it works fine. So I'm not entirely sure node-sass is the issue. Then again, this issue only happens on one of my machines and I'm not sure what else could be the root cause.
