### ISSUE TITLE
Error: Undefined variable: "$dl-horizontal-breakpoint".

### ISSUE THREAD

**Issue by ConorNugent** [aexmachina/ember-cli-sass#91]
Hi, I ran into a really weird issue yesterday that seems to me to be related to some external dependency braking our sass compilation. I first came across it when I tried to deploy to heroku. The build kept failing with the following compilation error

Error: Undefined variable: "$dl-horizontal-breakpoint".

I wasn't getting this locally which really threw me. My guess was it might be due to some variation in the way the dependencies are being pulled in. I cleared out my bower and npm caches and sure enough the same issue appeared  

File: /Users/conornugent/Dev/neighbourwood/neighbourwood-portal/tmp/sass_compiler-input_base_path-5rryynkr.tmp/0/app/styles/bootstrap/_type.scss (210)
Undefined variable: "$dl-horizontal-breakpoint".
Error: Undefined variable: "$dl-horizontal-breakpoint".

It looks like that bootstrap variable file and bootstrap in general isn't being complied properly anymore. What's really strange is that we haven't made any fundamental changes to the app, it really looks like an external dependency issue that just cropped in the last day or so.  I also tried upgrading our app from from 1.13.8 to 1.13.13 just in case but the same issue persisted.  Any ideas what might be up?

I case it helps, our updated dependencies; 

"devDependencies": {
"broccoli-asset-rev": "^2.2.0",
"ember-cli": "^1.13.13",
"ember-cli-app-version": "^1.0.0",
"ember-cli-babel": "^5.1.5",
"ember-cli-bootstrap-sassy": "0.0.18",
"ember-cli-content-security-policy": "0.4.0",
"ember-cli-dependency-checker": "^1.1.0",
"ember-cli-htmlbars": "^1.0.1",
"ember-cli-htmlbars-inline-precompile": "^0.3.1",
"ember-cli-ic-ajax": "0.2.4",
"ember-cli-inject-live-reload": "^1.3.1",
"ember-cli-moment-shim": "0.6.1",
"ember-cli-qunit": "^1.0.4",
"ember-cli-release": "0.2.8",
"ember-cli-sass": "5.2.0",
"ember-cli-simple-auth": "0.8.0",
"ember-cli-simple-auth-devise": "0.8.0",
"ember-cli-sri": "^1.2.0",
"ember-cli-uglify": "^1.2.0",
"ember-data": "1.13.15",
"ember-disable-proxy-controllers": "^1.0.1",
"ember-export-application-global": "^1.0.4",
"ember-highcharts": "0.1.3",
"ember-moment": "3.5.0",
"moment": "2.10.6",
"ui-ember-slider": "0.2.5"
}

**Comment by ConorNugent** [comment]
I think this issue might be related to way references to scss files outside of the styles file are being treated. We use bootstrap-sassy and had been pulling in our bootstrap styles via a _custom_bootstrap.scss file. It contains reference such 

@import "bootstrap/normalize";
@import "bootstrap/print";
@import "bootstrap/glyphicons";
etc.

This worked fine until 2 days ago. If I now pull bootstrap in its entirety by adding @bootstrap to our app.scss everything works but this is obviously less than ideal. It would be really good to get to the bottom of why our original setup suddenly stopped working. My guess is that files referenced as above are being recognised but not compiled properly. Does anyone have any ideas about the root of this issue and suggestions for a better fix?

**Comment by ConorNugent** [comment]
This was down to some changes to our _custom_bootstrap.scss that crept in under the radar. I'm sorry about the confusion and for clogging up your issues list with noise

**Comment by nolawi** [comment]
was this fixed

**Comment by aexmachina** [comment]
@nolawi it was not an issue to begin with. If you'd read the comment above yours you would have seen this pretty easily.

**Comment by emajen** [comment]
wow ^ way to be a....

@aexmachina if you were paying attention to what you were doing this post wouldn't be clogging up the radar. Rude...
