### ISSUE TITLE
Node-sass parsing issue 

### ISSUE THREAD

**Issue by linearza** [aexmachina/ember-cli-sass#92]
There is a known libsass parsing issue, where the output doesnt get compiled correctly, eg:

```
-webkit-transition: -webkit-transform, height;
  -moz-transition: -moz-transform, height;
  transition: transform, height;
```

It seems the solution for now is using an older version of node-sass until its resolved.
More info: https://github.com/sass/node-sass/issues/1227

Using this mixin is a temporary solution:
```
@mixin trans-prefix($value, $prefix: "") {
  $slice: str-slice(inspect($value), 0, 9);
  @if $slice == "transform" {
    #{$prefix}transition: #{$prefix}#{$value};
  } @else {
    #{$prefix}transition: $value;
  }
}
@mixin transition($properties...) {
  @if length($properties) > 1 {
    $spec:              ();
    @for $i from 1 through length($properties) {
      $spec:            append($spec, nth($properties, $i), comma);
    }
  } @else {
    $spec:              $properties;
  }
  @include trans-prefix($spec, -webkit-);
  @include trans-prefix($spec, -moz-);
  @include trans-prefix($spec);
}
```

**Comment by aexmachina** [comment]
You can specify [a version of node-sass to use](https://github.com/aexmachina/broccoli-sass-source-maps#usage) using the options.

**Comment by linearza** [comment]
Thank you.

**Comment by kaurmanvir** [comment]
why is this issue not fixed in latest version? I do not want to downgrade my version

**Comment by aexmachina** [comment]
There are good reasons why we do it this way. You have complete control over the version of node-sass using the [nodeSass option](https://github.com/aexmachina/broccoli-sass-source-maps#usage).
