### ISSUE TITLE
Getting SIGSEGV error

### ISSUE THREAD

**Issue by krzkrzkrz** [aexmachina/ember-cli-sass#97]
Installing this on Ember CLI 1.13.13, via `ember install ember-cli-sass`.

`package.json` has `"ember-cli-sass": "^5.2.1"`. When I execute `ember server`, I get:

```
'ember server' terminated by signal SIGSEGV (Address boundary error)
```

Removing `"ember-cli-sass": "^5.2.1"` from `package.json` starts `ember server` fine. 

Any reason why this is happening?

**Comment by krzkrzkrz** [comment]
Issue was related to some SASS elements undefined properly. Closing for now

**Comment by hugoruscitti** [comment]
I had the same issue today, i fixed by removing node_modules and bower_components and reinstall again.
