### ISSUE TITLE
Is Ember CLI Sass not generating the right fingerprint?

### ISSUE THREAD

**Issue by krzkrzkrz** [aexmachina/ember-cli-sass#98]
Anyone experience this before. 

I have `@include background(url("images/landing.jpg") top left no-repeat);` in a `scss` file. This renders fine locally.

When I do: `ember build --environment=staging`

I inspect the dist files. It points to https://cdn1.site-name.com/dist/team/assets/images/landing-72fbd7209b47110bc5248eb1db013e4e.jpg instead of https://cdn1-staging.site-name.com/dist/team/assets/images/landing-72fbd7209b47110bc5248eb1db013e4e.jpg

Note, `cdn1` instead of `cdn1-staging`.

`ember-cli-build.js` has:

```
module.exports = function(defaults) {
  var env = EmberApp.env();
  var isProductionLikeBuild = ['production', 'staging'].indexOf(env) > -1;

  var app = new EmberApp(defaults, {
    // Add options here
    fingerprint: {
      enabled: isProductionLikeBuild,
      prepend: 'https://cdn1' + (env === 'staging' ? '-staging' : '') + '.site-name.com/dist/team/'
    },
    sourcemaps: {
      enabled: !isProductionLikeBuild,
    },
    minifyCSS: { enabled: isProductionLikeBuild },
    minifyJS: { enabled: isProductionLikeBuild }
  });
```

**Comment by stefanpenner** [comment]
Fingerprinting is unrelated to this. You like want to open an issue on broccoli-asset-rev

**Comment by krzkrzkrz** [comment]
Strange thing. I did `ember build --environment=development` then `rm -rf /dist`, then `ember build —environment=staging`.

The first `ember build` must have cleared out some caching. `ember build —environment=staging` now works as expected. Not sure how/why.

Closing for now.

**Comment by stefanpenner** [comment]
> ember build —environment=staging now works as expected. Not sure how/why.

there is no concept of `staging` in ember-cli, we only support test/development/production. If you wish to customize those further, please use environment variables.
